//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMClothsStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class apply
    {
        public apply()
        {
            this.applyDetail = new HashSet<applyDetail>();
        }
    
        public string applyId { get; set; }
        public string outShop { get; set; }
        public string inShop { get; set; }
        public string state { get; set; }
        public Nullable<System.DateTime> applyTime { get; set; }
    
        public virtual shop shop { get; set; }
        public virtual shop shop1 { get; set; }
        public virtual ICollection<applyDetail> applyDetail { get; set; }
    }
}
