//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMClothsStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class check
    {
        public check()
        {
            this.checkDetail = new HashSet<checkDetail>();
        }
    
        public string checkId { get; set; }
        public string shopId { get; set; }
        public string checkerId { get; set; }
        public Nullable<System.DateTime> checkTime { get; set; }
    
        public virtual shop shop { get; set; }
        public virtual staff staff { get; set; }
        public virtual ICollection<checkDetail> checkDetail { get; set; }
    }
}
