//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMClothsStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public item()
        {
            this.applyDetail = new HashSet<applyDetail>();
            this.checkDetail = new HashSet<checkDetail>();
            this.inDetail = new HashSet<inDetail>();
            this.orderDetail = new HashSet<orderDetail>();
            this.outDetail = new HashSet<outDetail>();
        }
    
        public string itemId { get; set; }
        public string itemName { get; set; }
        public string itemSize { get; set; }
        public string itemColor { get; set; }
        public string itemImage { get; set; }
        public Nullable<decimal> itemPrice { get; set; }
        public Nullable<System.DateTime> itemDate { get; set; }
    
        public virtual ICollection<applyDetail> applyDetail { get; set; }
        public virtual ICollection<checkDetail> checkDetail { get; set; }
        public virtual image image { get; set; }
        public virtual ICollection<inDetail> inDetail { get; set; }
        public virtual ICollection<orderDetail> orderDetail { get; set; }
        public virtual ICollection<outDetail> outDetail { get; set; }
        public virtual stock stock { get; set; }
    }
}
