//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMClothsStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YMEntities : DbContext
    {
        public YMEntities()
            : base("name=YMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<address> address { get; set; }
        public DbSet<apply> apply { get; set; }
        public DbSet<applyDetail> applyDetail { get; set; }
        public DbSet<check> check { get; set; }
        public DbSet<checkDetail> checkDetail { get; set; }
        public DbSet<image> image { get; set; }
        public DbSet<@in> @in { get; set; }
        public DbSet<inDetail> inDetail { get; set; }
        public DbSet<item> item { get; set; }
        public DbSet<order> order { get; set; }
        public DbSet<orderDetail> orderDetail { get; set; }
        public DbSet<@out> @out { get; set; }
        public DbSet<outDetail> outDetail { get; set; }
        public DbSet<shop> shop { get; set; }
        public DbSet<staff> staff { get; set; }
        public DbSet<stock> stock { get; set; }
    }
}
