//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMClothsStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public order()
        {
            this.orderDetail = new HashSet<orderDetail>();
        }
    
        public string orderId { get; set; }
        public string shopId { get; set; }
        public Nullable<decimal> totalPrice { get; set; }
        public Nullable<System.DateTime> orderTime { get; set; }
    
        public virtual shop shop { get; set; }
        public virtual ICollection<orderDetail> orderDetail { get; set; }
    }
}
