//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMClothsStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop
    {
        public shop()
        {
            this.apply = new HashSet<apply>();
            this.apply1 = new HashSet<apply>();
            this.check = new HashSet<check>();
            this.inBase = new HashSet<inBase>();
            this.order = new HashSet<order>();
            this.outBase = new HashSet<outBase>();
            this.staff = new HashSet<staff>();
            this.stock = new HashSet<stock>();
        }
    
        public string shopId { get; set; }
        public string shopAddress { get; set; }
        public decimal shopStatus { get; set; }
        public string shopPhone { get; set; }
    
        public virtual address address { get; set; }
        public virtual ICollection<apply> apply { get; set; }
        public virtual ICollection<apply> apply1 { get; set; }
        public virtual ICollection<check> check { get; set; }
        public virtual ICollection<inBase> inBase { get; set; }
        public virtual ICollection<order> order { get; set; }
        public virtual ICollection<outBase> outBase { get; set; }
        public virtual ICollection<staff> staff { get; set; }
        public virtual ICollection<stock> stock { get; set; }
    }
}
