//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YMClothsStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public staff()
        {
            this.check = new HashSet<check>();
            this.@in = new HashSet<@in>();
            this.@out = new HashSet<@out>();
        }
    
        public string staffId { get; set; }
        public string staffName { get; set; }
        public string staffGender { get; set; }
        public string staffPhone { get; set; }
        public Nullable<decimal> staffJob { get; set; }
        public string shopId { get; set; }
        public string staffLoginName { get; set; }
        public string password { get; set; }
    
        public virtual ICollection<check> check { get; set; }
        public virtual ICollection<@in> @in { get; set; }
        public virtual ICollection<@out> @out { get; set; }
        public virtual shop shop { get; set; }
    }
}
